baseurl = "/"
languageCode = "en-gb"
languageLang = "en-gb"
title = "Delyn Packaging"
disableKinds = ["RSS"]
googleAnalytics = ""

[taxonomies]
  type = "types"
  category = "categories"

[permalinks]
  pages = "/:title"
  posts = "/:title"

[params]
  logo = "delyn-logo.svg"
  headerImage = "/img/home-header-bg-lg.jpg"
  