backend:
  name: git-gateway

media_folder: "src/img/"
public_folder: "/img/"

collections:
  - label: "Settings"
    name: "settings"
    files:
      - name: "social"
        label: "Social Media"
        file: "data/social.yml"
        extension: "yml"
        fields:
          - label: "Social Media"
            name: "social"
            widget: "list"
            fields:
              - {label: "Name", name: "name", widget: "string"}
              - {label: "Link (URL)", name: "url", widget: "string"}
              - {label: "FontAwesome Icon Name (without fa*-)", name: "icon", widget: "string"}
      
  - name: "posts"
    label: "News"
    folder: "site/content/posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    filter:
      field: menu
      value:
    fields:
    - {label: "Title", name: "title", widget: "string"}
    - {label: "Publish Date", name: "date", widget: "datetime", data}
    - {label: "Featured Image", name: "headerimage", widget: "image"}
    - {label: "Body", name: "body", widget: "markdown"}